(()=>{
'use strict';
const WS='wss://api.upbit.com/websocket/v1', REST='https://api.upbit.com/v1/trades/ticks', M='KRW-XRP';
const TARGET=120000,BATCH=500,DELAY=280,MAX=620,VW=20,LB=3,FLAT=.02,CONV=.25,KEY='xrp_v4';
const $=id=>document.getElementById(id),E={conn:$('conn'),price:$('price'),count:$('count'),save:$('save'),v:$('vwapState'),sig:$('signal'),hist:$('history'),hb:$('histbar'),p240:$('p240'),p960:$('p960'),c240:$('c240'),c960:$('c960'),re:$('reconnect')};
let ws=null,seq=0,lastSid=null,live=0,timer=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function B(size){this.size=size;this.done=[];this.cur=null}
B.prototype.add=function(t){let gid=Math.floor(t.seq/this.size);if(!this.cur||this.cur.gid!==gid){if(this.cur){this.cur.complete=this.cur.count>=this.size;this.done.push(this.cur);if(this.done.length>MAX)this.done.shift()}this.cur={gid,open:t.p,high:t.p,low:t.p,close:t.p,volume:t.q,start:t.ts,end:t.ts,count:1,complete:false}}else{let b=this.cur;b.high=Math.max(b.high,t.p);b.low=Math.min(b.low,t.p);b.close=t.p;b.volume+=t.q;b.end=t.ts;b.count++}if(this.cur&&this.cur.count>=this.size){this.cur.complete=true;this.done.push(this.cur);if(this.done.length>MAX)this.done.shift();this.cur=null}};
const C={240:new B(240),960:new B(960)};
const bars=b=>{let a=b.done.slice();if(b.cur)a.push({...b.cur});return a};
function ema(v,s){if(!v.length)return[];let k=2/(s+1),e=v[0],o=[e];for(let i=1;i<v.length;i++){e=v[i]*k+e*(1-k);o.push(e)}return o}
function vwap20(a){let o=[],q=[],pvS=0,vS=0;for(let b of a){let typ=(b.high+b.low+b.close)/3,vol=+b.volume||0,pv=typ*vol;q.push([pv,vol]);pvS+=pv;vS+=vol;if(q.length>VW){let z=q.shift();pvS-=z[0];vS-=z[1]}o.push(vS?pvS/vS:b.close)}return o}
function ind(a){let c=a.map(x=>x.close);return{e5:ema(c,5),e10:ema(c,10),e20:ema(c,20),e60:ema(c,60),e120:ema(c,120),vwap:vwap20(a)}}
function slope(v){if(v.length<LB+1)return{state:'FLAT',pct:0};let n=v.at(-1),b=v[v.length-1-LB],p=b?(n/b-1)*100:0;return{state:p>FLAT?'UP':p<-FLAT?'DOWN':'FLAT',pct:p}}
function arrows(a,I){let o=[];for(let i=1;i<a.length;i++){let px=a[i].close||1,span=(Math.max(I.e5[i],I.e10[i],I.e20[i])-Math.min(I.e5[i],I.e10[i],I.e20[i]))/px*100;if(span>CONV)continue;let up=I.e5[i-1]<=I.vwap[i-1]&&I.e5[i]>I.vwap[i],dn=I.e5[i-1]>=I.vwap[i-1]&&I.e5[i]<I.vwap[i];if(up)o.push([i,'UP',a[i].low]);if(dn)o.push([i,'DOWN',a[i].high])}return o}
function sig(){let a=C[240].done;if(a.length<22)return{state:'FLAT',pct:0,label:'WAIT',cls:'wait'};let I=ind(a),i=a.length-1,p=i-1,S=slope(I.vwap),px=a[i].close||1,span=(Math.max(I.e5[i],I.e10[i],I.e20[i])-Math.min(I.e5[i],I.e10[i],I.e20[i]))/px*100,cv=span<=CONV,up=I.e5[p]<=I.vwap[p]&&I.e5[i]>I.vwap[i],dn=I.e5[p]>=I.vwap[p]&&I.e5[i]<I.vwap[i];if(S.state==='UP'&&cv&&up)return{...S,label:'BUY 후보 ↑',cls:'buy'};if(S.state==='DOWN'&&cv&&dn)return{...S,label:'SELL 후보 ↓',cls:'sell'};if(S.state==='UP')return{...S,label:'HOLD / BUY 허가',cls:'buy'};if(S.state==='DOWN')return{...S,label:'BUY 차단 / SELL 관찰',cls:'sell'};return{...S,label:'WAIT',cls:'wait'}}
function arrow(ctx,x,y,d){ctx.fillStyle=d==='UP'?'#0a8f3c':'#c62828';ctx.beginPath();if(d==='UP'){ctx.moveTo(x,y-12);ctx.lineTo(x-8,y-2);ctx.lineTo(x-3,y-2);ctx.lineTo(x-3,y+8);ctx.lineTo(x+3,y+8);ctx.lineTo(x+3,y-2);ctx.lineTo(x+8,y-2)}else{ctx.moveTo(x,y+12);ctx.lineTo(x-8,y+2);ctx.lineTo(x-3,y+2);ctx.lineTo(x-3,y-8);ctx.lineTo(x+3,y-8);ctx.lineTo(x+3,y+2);ctx.lineTo(x+8,y+2)}ctx.closePath();ctx.fill()}
function draw(cv,a){let d=Math.max(1,devicePixelRatio||1),r=cv.getBoundingClientRect(),ctx=cv.getContext('2d');cv.width=r.width*d;cv.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);let W=r.width,H=r.height;ctx.clearRect(0,0,W,H);let pad={l:46,r:12,t:12,b:22},pw=W-pad.l-pad.r,ph=H-pad.t-pad.b;if(a.length<2){ctx.fillStyle='#777';ctx.fillText('과거/실시간 체결 준비 중...',18,32);return}a=a.slice(-180);let I=ind(a),v=[];a.forEach(b=>v.push(b.high,b.low));Object.values(I).forEach(s=>s.forEach(x=>Number.isFinite(x)&&v.push(x)));let mn=Math.min(...v),mx=Math.max(...v),ex=(mx-mn)*.08||1;mn-=ex;mx+=ex;let X=i=>pad.l+(i+.5)*(pw/a.length),Y=x=>pad.t+(mx-x)/(mx-mn)*ph;ctx.strokeStyle='#ececec';for(let g=0;g<=5;g++){let yy=pad.t+ph*g/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(W-pad.r,yy);ctx.stroke()}let cw=Math.max(2,Math.min(7,pw/a.length*.68));a.forEach((b,i)=>{let up=b.close>=b.open,c=up?'#e65d5d':'#4b82e8';ctx.strokeStyle=c;ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(X(i),Y(b.high));ctx.lineTo(X(i),Y(b.low));ctx.stroke();let yo=Y(b.open),yc=Y(b.close);ctx.fillRect(X(i)-cw/2,Math.min(yo,yc),cw,Math.max(1,Math.abs(yc-yo)))});[['e5','#2f80ed',1.2],['e10','#f2994a',1.2],['e20','#27ae60',1.4],['e60','#eb5757',1.3],['e120','#9b51e0',1.3],['vwap','#8d5a44',2.8]].forEach(([k,c,l])=>{ctx.strokeStyle=c;ctx.lineWidth=l;ctx.setLineDash(k==='vwap'?[7,5]:[]);ctx.beginPath();I[k].forEach((z,i)=>i?ctx.lineTo(X(i),Y(z)):ctx.moveTo(X(i),Y(z)));ctx.stroke();ctx.setLineDash([])});arrows(a,I).forEach(s=>arrow(ctx,X(s[0]),Y(s[2])+(s[1]==='UP'?16:-16),s[1]));ctx.fillStyle='#555';ctx.font='11px sans-serif';ctx.fillText(mx.toFixed(1),3,pad.t+4);ctx.fillText(mn.toFixed(1),3,pad.t+ph)}
function render(){draw(E.c240,bars(C[240]));draw(E.c960,bars(C[960]));E.p240.textContent=`${C[240].cur?.count||0}/240 · 완성 ${C[240].done.length}`;E.p960.textContent=`${C[960].cur?.count||0}/960 · 완성 ${C[960].done.length}`;let s=sig();E.v.textContent=`VWAP20 ${s.state} ${s.pct>=0?'+':''}${s.pct.toFixed(3)}%`;E.v.className='badge '+(s.state==='UP'?'up':s.state==='DOWN'?'down':'flat');E.sig.textContent=s.label;E.sig.className='signal '+s.cls}
function add(r){let t={p:+r.trade_price,q:+r.trade_volume||0,s:r.ask_bid||'',ts:+r.timestamp||Date.now(),sid:r.sequential_id??null,seq:seq++};C[240].add(t);C[960].add(t);if(t.sid!=null)lastSid=t.sid}
function save(){try{localStorage.setItem(KEY,JSON.stringify({v:4,seq,lastSid,b240:C[240],b960:C[960]}));E.save.textContent='자동 저장됨'}catch(e){}}
function load(){try{let s=JSON.parse(localStorage.getItem(KEY)||'null');if(!s||s.v!==4)return false;seq=s.seq||0;lastSid=s.lastSid??null;Object.assign(C[240],s.b240||{});Object.assign(C[960],s.b960||{});return C[240].done.length||C[960].done.length}catch(e){return false}}
async function history(target,stop=null,maxPages=300){let rows=[],cursor=null;for(let pg=0;pg<maxPages&&rows.length<target;pg++){let u=new URL(REST);u.searchParams.set('market',M);u.searchParams.set('count',BATCH);if(cursor!=null)u.searchParams.set('cursor',cursor);let r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);let a=await r.json();if(!a.length)break;for(let z of a){if(stop!=null&&String(z.sequential_id)===String(stop)){rows.reverse();return rows}rows.push(z);if(rows.length>=target)break}cursor=a.at(-1)?.sequential_id;E.hist.textContent=`과거체결 ${rows.length.toLocaleString()}/${target.toLocaleString()}`;E.hb.textContent=`${Math.min(100,rows.length/target*100).toFixed(0)}%`;await sleep(DELAY)}rows.reverse();return rows}
async function prefill(){E.conn.textContent='과거데이터 준비';try{let rows=await history(TARGET);C[240].done=[];C[240].cur=null;C[960].done=[];C[960].cur=null;seq=0;lastSid=null;for(let i=0;i<rows.length;i++){add(rows[i]);if(i%5000===0){E.hist.textContent=`봉 생성 ${i.toLocaleString()}/${rows.length.toLocaleString()}`;render();await sleep(0)}}E.hist.textContent=`과거 ${rows.length.toLocaleString()}건 · 240T ${C[240].done.length}봉 · 960T ${C[960].done.length}봉`;E.hb.textContent='100%';save();render()}catch(e){console.warn(e);E.hist.textContent='과거데이터 실패 · 실시간부터 시작';E.hb.textContent='실패'}}
async function gap(){if(lastSid==null)return;try{let rows=await history(50000,lastSid,110);rows.forEach(add);if(rows.length){E.hist.textContent=`누락 ${rows.length.toLocaleString()}건 보충`;save();render()}}catch(e){console.warn(e)}}
async function parse(d){try{if(d instanceof Blob)return JSON.parse(await d.text());if(d instanceof ArrayBuffer)return JSON.parse(new TextDecoder().decode(d));return JSON.parse(d)}catch(e){return null}}
function connect(){if(ws)try{ws.close()}catch(e){}E.conn.textContent='연결 중';ws=new WebSocket(WS);ws.binaryType='arraybuffer';ws.onopen=()=>{ws.send(JSON.stringify([{ticket:'xrp-v4-'+Date.now()},{type:'trade',codes:[M],is_only_realtime:true},{format:'DEFAULT'}]));E.conn.textContent='실시간 연결';E.conn.className='badge up'};ws.onmessage=async ev=>{let m=await parse(ev.data);if(!m||m.type!=='trade'||m.code!==M)return;if(lastSid!=null&&m.sequential_id!=null&&String(m.sequential_id)===String(lastSid))return;add(m);live++;E.price.textContent=`${(+m.trade_price).toLocaleString()} KRW`;E.count.textContent=`실시간 ${live.toLocaleString()}`;render();clearTimeout(timer);timer=setTimeout(save,1000)};ws.onclose=()=>setTimeout(connect,3000)}
async function start(){if(load()){E.hist.textContent=`저장 복원 · 240T ${C[240].done.length}봉 · 960T ${C[960].done.length}봉`;E.hb.textContent='100%';render();await gap()}else await prefill();connect()}
E.re.onclick=async()=>{await gap();connect()};addEventListener('resize',render);document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'){await gap();if(!ws||ws.readyState>1)connect()}else save()});addEventListener('beforeunload',save);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});start();setInterval(render,1000);
})();